init:
  - git config --global core.autocrlf input

version: 0.1.{build}

skip_tags: true

build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "All"

image: Visual Studio 2017

test: off

artifacts:
  - path: Build\Packages\*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: +YlrKmWps7RJVPU4s7B4HWNL9cZXaUVdiNJInli9IZPlTP+J0CyHsUvcDY8haE+b
    skip_symbols: false
    on:
      branch: master